version: "3.9"
services:
        sslh:
                image: riftbit/sslh:debian-select
                network_mode: "host"
                environment:
                        - SSLH_OPTS=-p 0.0.0.0:443 --ssh 0.0.0.0:22 --ssl 0.0.0.0:8443

                depends_on:
                        - nginx-reverse
        nginx-reverse:
                image: nginx:latest
                volumes:
                        - [[O_KEYS_DIRECTORY]]:/keys
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "8443:443"
                        - "8080:80"
                networks:
                        - homebase
        transmission:
                image: lscr.io/linuxserver/transmission
                volumes:
                        - [[V_TRANSMISSION_CONFIG]]:/config
                        - [[V_TRANSMISSION_DOWNLOADS]]:/downloads
                networks:
                        - homebase
        ubuntu-vnc:
                build:
                        context: ./ubuntu-vnc
                        dockerfile: ./Dockerfile
                environment:
                        - RELATIVE_URL_ROOT=vnc
                        - HTTP_PASSWORD=[[E_UBUNTU_VNC_HTTP_PASSWORD]]
                        - USER=[[E_UBUNTU_VNC_USERNAME]]
                        - PASSWORD=[[E_UBUNTU_VNC_PASSWORD]]
                volumes:
                        - [[V_UBUNTU_VNC_HOME_DIR]]:/home/[[E_UBUNTU_VNC_USERNAME]]
                networks:
                        - homebase
networks:
        homebase:
                driver: bridge        
