version: "3.9"
services:
        nginx-reverse:
                image: nginx:latest
                volumes:
                        - /path/to/keys:/keys:ro
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
                        - ./nginx/www:/www:ro
                ports:
                        - "443:443"
                        - "80:80"
                networks:
                        - homebase
                restart: always
        transmission:
                image: lscr.io/linuxserver/transmission
                volumes:
                        - /path/to/transmission/config:/config
                        - /path/to/transmission/downloads:/downloads
                networks:
                        - homebase
                restart: always
        vaultwarden:
                image: vaultwarden/server:latest
                environment:
                        - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
                        - DOMAIN=https://homebase/vault/
                volumes:
                        - /path/to/vw/data:/data
                networks:
                        - homebase
                restart: always
        airsonic:
                image: airsonic/airsonic:latest
                environment:
                       - CONTEXT_PATH=/airsonic
                group_add:
                       - audio
                devices:
                       - /dev/snd
                volumes:
                       - ./airsonic/sound.properties:/usr/lib/jvm/java-1.8-openjdk/jre/lib/sound.properties
                       - /path/to/airsonic/data:/airsonic/data
                       - /path/to/airsonic/music:/airsonic/music
                       - /path/to/airsonic/podcasts:/airsonic/podcasts
                       - /path/to/airsonic/playlists:/airsonic/playlists
                networks:
                        - homebase
                restart: always
networks:
        homebase:
                driver: bridge        
                ipam:
                        driver: default
                        config:
                                - subnet: 172.28.0.0/16
                                  gateway: 172.28.0.1
